# Specify the base image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to app directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the Express.js server will run
EXPOSE 3000

# Start the Express.js server
CMD ["npm", "run" , "dev"]